name: Node CI

on:
  push:
    branches:
      - master
    paths:
      - hello-world/**


jobs:  
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Sparse checkout
      run: |
        git init static
        cd static
        git remote add origin https://github.com/sarath9985/nodejs.git
        git config core.sparsecheckout true
        echo "hello-world/*" >> .git/info/sparse-checkout
        git pull --depth=1 origin master
        ls -la

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, build, and test
      run: |
        node -v
        cd static/hello-world
        npm install
        npm build
        ls -la
