name: Node CI

on:
  push:
    branches:
      - master
    paths:
      - hello-world/**


jobs:  
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Sparse checkout
      run: |
        git init static
        cd static
        git remote add origin https://github.com/sarath9985/nodejs.git
        git config core.sparsecheckout true
        echo "hello-world/*" >> .git/info/sparse-checkout
        git pull --depth=1 origin master

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, build, and test
      run: |
        node -v
        npm install -g gatsby-cli
        cd static/hello-world
        npm install
        gatsby build
        ls -la

    - name: list files
      run: |
        ls -la

    - name: Upload to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'  
        SOURCE_DIR: 'static/hello-world/public'
